In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# read in the merged table of weather and taxi data
df = pd.read_csv('../data/curated/final_data_new')

In [3]:
df.describe()

,Unnamed: 0,PULocationID,income_rate,total_adjusted_amount,trip_distance,fare_amount,tip_amount,tempmin,tempmax,temp,precip,precipcover,windgust,windspeed,dew,humidity,snow,snowdepth,cloudcover,visibility
count,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000,52822.000000
mean,26410.500000,136.697096,1.312912,10.911143,1.676207,8.476688,1.146962,1.236116,7.532507,4.372241,3.227718,12.396084,37.991606,24.144078,-2.858082,61.596573,0.555202,1.074774,54.229137,14.433301
std,15248.542296,76.435149,4.154576,2.312267,0.556118,1.882518,0.539908,5.391327,6.090704,5.612606,6.745659,19.565999,18.566792,8.237524,7.326277,14.648653,1.671324,2.985801,26.344513,2.494705
min,0.000000,1.000000,0.000000,2.500000,0.010000,2.500000,0.000000,-14.900000,-10.700000,-12.200000,0.000000,0.000000,0.000000,9.800000,-22.600000,33.900000,0.000000,0.000000,2.900000,4.000000
25%,13205.250000,70.000000,0.920897,9.950000,1.410968,7.666667,0.894336,-1.900000,3.900000,1.100000,0.000000,0.000000,33.500000,17.700000,-7.100000,49.900000,0.000000,0.000000,30.900000,13.700000
50%,26410.500000,139.000000,0.995279,10.899613,1.595000,8.375000,1.260000,2.100000,7.600000,4.800000,0.000000,0.000000,42.400000,22.800000,-2.800000,59.700000,0.000000,0.000000,53.100000,15.800000
75%,39615.750000,203.000000,1.081077,11.779075,1.885000,9.166667,1.500000,4.500000,11.400000,7.600000,2.630000,20.830000,50.000000,28.700000,2.000000,72.200000,0.000000,0.200000,76.200000,16.000000
max,52821.000000,265.000000,493.800000,42.130288,4.040000,18.540000,5.310288,17.900000,25.800000,19.500000,38.240000,95.830000,74.000000,46.800000,16.700000,95.800000,10.700000,17.700000,100.000000,16.000000

In [4]:
# split data into response(income_rate) and the remainders as predictors
X = df[['PULocationID','total_adjusted_amount','trip_distance','fare_amount','tip_amount',
       "tempmin","tempmax","temp","precip","precipcover","windgust","windspeed",
                     "dew","humidity","snow","snowdepth","cloudcover","visibility"]]

In [5]:
y = df[['income_rate']]

In [6]:
# split training set and validation set chronologically
X_train, X_test, y_train, y_test = train_test_split(X, y,
    test_size=0.4, shuffle = False)

In [7]:
# equally split the validation set and testing set, shuffle split to make sure more equal distributions between two sets
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, 
    test_size=0.5, shuffle = True, random_state= 42)

In [8]:
X_train

,PULocationID,total_adjusted_amount,trip_distance,fare_amount,tip_amount,tempmin,tempmax,temp,precip,precipcover,windgust,windspeed,dew,humidity,snow,snowdepth,cloudcover,visibility
0,1,17.300000,0.200000,17.000000,0.000000,4.1,8.0,5.8,0.0,0.0,37.1,22.0,-5.1,45.8,0.0,0.0,51.0,16.0
1,4,11.791397,1.767352,9.058118,1.545000,4.1,8.0,5.8,0.0,0.0,37.1,22.0,-5.1,45.8,0.0,0.0,51.0,16.0
2,7,10.018121,1.596759,7.714427,1.046629,4.1,8.0,5.8,0.0,0.0,37.1,22.0,-5.1,45.8,0.0,0.0,51.0,16.0
3,8,11.745294,2.463333,9.500000,1.550000,4.1,8.0,5.8,0.0,0.0,37.1,22.0,-5.1,45.8,0.0,0.0,51.0,16.0
4,10,16.391960,3.130000,12.400000,2.000000,4.1,8.0,5.8,0.0,0.0,37.1,22.0,-5.1,45.8,0.0,0.0,51.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31688,52,10.571974,1.401545,7.898374,1.450000,-4.9,1.2,-1.9,0.0,0.0,40.7,24.9,-15.0,38.3,0.0,0.0,16.0,16.0
31689,54,9.772281,1.347778,7.277778,1.000000,-4.9,1.2,-1.9,0.0,0.0,40.7,24.9,-15.0,38.3,0.0,0.0,16.0,16.0
31690,55,12.378158,1.800000,10.666667,1.134186,-4.9,1.2,-1.9,0.0,0.0,40.7,24.9,-15.0,38.3,0.0,0.0,16.0,16.0
31691,56,8.045766,1.400000,6.500000,0.745766,-4.9,1.2,-1.9,0.0,0.0,40.7,24.9,-15.0,38.3,0.0,0.0,16.0,16.0
31692,61,12.075521,1.982000,9.414286,1.560000,-4.9,1.2,-1.9,0.0,0.0,40.7,24.9,-15.0,38.3,0.0,0.0,16.0,16.0

In [10]:
# to remove PULocationID
train = X_train[X_train.columns[1:]]

In [19]:
train

,total_adjusted_amount,trip_distance,fare_amount,tip_amount,tempmin,tempmax,temp,precip,precipcover,windgust,windspeed,dew,humidity,snow,snowdepth,cloudcover,visibility
0,17.300000,0.200000,17.000000,0.000000,4.1,8.0,5.8,0.0,0.0,37.1,22.0,-5.1,45.8,0.0,0.0,51.0,16.0
1,11.791397,1.767352,9.058118,1.545000,4.1,8.0,5.8,0.0,0.0,37.1,22.0,-5.1,45.8,0.0,0.0,51.0,16.0
2,10.018121,1.596759,7.714427,1.046629,4.1,8.0,5.8,0.0,0.0,37.1,22.0,-5.1,45.8,0.0,0.0,51.0,16.0
3,11.745294,2.463333,9.500000,1.550000,4.1,8.0,5.8,0.0,0.0,37.1,22.0,-5.1,45.8,0.0,0.0,51.0,16.0
4,16.391960,3.130000,12.400000,2.000000,4.1,8.0,5.8,0.0,0.0,37.1,22.0,-5.1,45.8,0.0,0.0,51.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31688,10.571974,1.401545,7.898374,1.450000,-4.9,1.2,-1.9,0.0,0.0,40.7,24.9,-15.0,38.3,0.0,0.0,16.0,16.0
31689,9.772281,1.347778,7.277778,1.000000,-4.9,1.2,-1.9,0.0,0.0,40.7,24.9,-15.0,38.3,0.0,0.0,16.0,16.0
31690,12.378158,1.800000,10.666667,1.134186,-4.9,1.2,-1.9,0.0,0.0,40.7,24.9,-15.0,38.3,0.0,0.0,16.0,16.0
31691,8.045766,1.400000,6.500000,0.745766,-4.9,1.2,-1.9,0.0,0.0,40.7,24.9,-15.0,38.3,0.0,0.0,16.0,16.0
31692,12.075521,1.982000,9.414286,1.560000,-4.9,1.2,-1.9,0.0,0.0,40.7,24.9,-15.0,38.3,0.0,0.0,16.0,16.0

In [14]:
### F-test for train 
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest, f_regression
SKB = SelectKBest(f_regression, k = 8)
X_new_train = SKB.fit_transform(train,y_train)
cols = SKB.get_support(indices=True)
selected_columns = train.iloc[:,cols].columns.tolist()
selected_columns

/opt/miniconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

['total_adjusted_amount',
 'trip_distance',
 'fare_amount',
 'tip_amount',
 'precipcover',
 'humidity',
 'cloudcover',
 'visibility']

In [15]:
SKB.scores_

array([3.23017163e+03, 6.83985664e+02, 6.76351161e+02, 1.16406271e+03,
       3.87460397e-03, 8.65930899e-02, 2.27706316e-05, 2.80442931e-02,
       1.77626164e+00, 2.43978580e-01, 6.55540697e-03, 3.92245341e-01,
       2.37951482e+00, 8.98659299e-02, 6.73319134e-02, 2.98904279e+00,
       1.39835429e+00])

In [17]:
# Standardise by sklearn
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
X_train.iloc[:, 1:] = SS.fit_transform(X_train.iloc[:, 1:])

/opt/miniconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1835: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

In [18]:
# store train/val/test set
X_train.to_csv('../data/curated/X_train')
y_train.to_csv('../data/curated/y_train')
X_val.to_csv('../data/curated/X_val')
y_val.to_csv('../data/curated/y_val')
X_test.to_csv('../data/curated/X_test')
y_test.to_csv('../data/curated/y_test')